name: WesternProject
version: '${project.version}'
main: droiidpelaez.westernproject.Core
api-version: 1.19
authors: [ Droiid ]
description: A collage of minecraft plugins for a western themed minecraft server
commands:
  eco:
  toggleplayerinfo:
    aliases:
      - tinfo
  withdraw:
  deposit:
  role:
  giveGold:
  balance:
    aliases:
      - bal
  drop:
    aliases:
      - dm
  team:

  wallet:
    aliases:
      - wa

